server:
    port: 8080
spring:
    freemarker:
        template-loader-path:
        - /templates/
        - file:./templates/
        cache: false
        settings:
            classic_compatible: true #处理空值
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##

    datasource:
        url: jdbc:mysql://localhost:3306/dblogftl?useSSL=false&characterEncoding=utf8
        username: root
        password: 123456hao123
    jpa:
        database: mysql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ./indexes
        open-in-view: true

    servlet:
        multipart:
            max-file-size: 5MB

    mail:
        host: smtp.exmail.qq.com
        username: example@mtons.com
        password: {your password}
        port: 25
        properties:
            mail.smtp.auth: true
            mail.smtp.ssl.enable: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true

#修改 `site.store.root` 属性, windows 用户记得地址要带盘符, linux 用户不带 (如果不将图片存储到部署目录外使用默认配置即可)
site.store.root: e:/data/mblog
# 存储模式, 可选值 absolute / relative
#site.store.repo` 存储模式 absolute (绝对路径存储, 系统将图片保存在{site.store.root}目录下}) / relative (相对路径存储,系统将图片存在部署目录下)
site.store.repo: relative

# 是否开启资源域名
site.store.domain: false

# ---------------------------------
# 资源域名, resource.domain = true 是有效
# 配置域名, 将域名的根目录指向 store.root 配置的地址
# ---------------------------------
site.store.host: http://localhost:8080/mblog